services:
  postgres:
    image: postgres:16
    container_name: jobtracker-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: jobtracker
      POSTGRES_PASSWORD: jobtracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
